version: '3.12'
services:
  postgres:
    image: postgres:16
    env_file:
      - ./src/.env
    ports:
      - "5432:5432"
    volumes:
      - './postgres-data:/var/lib/postgresql/data'

  app:
    build:
      context: ./src/django_app
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - './src/django_app:/django_app'
    env_file:
      - ./src/.env
    depends_on:
      - postgres
    links:
      - postgres
