# Generated by Django 5.0.4 on 2024-04-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipaddress",
            name="subnet",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
