# Generated by Django 5.0.4 on 2024-04-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0002_alter_ipaddress_subnet"),
    ]

    operations = [
        migrations.AddField(
            model_name="pingstat",
            name="packet_loss",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
