name: Project CI

on:
  push:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Cache Poetry virtualenv
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -

    - name: Configure Poetry
      run: |
        $HOME/.local/bin/poetry config virtualenvs.create false  # Optional: Configure Poetry to not create a virtual environment

    - name: Install dependencies
      run: $HOME/.local/bin/poetry install

    - name: Run tests
      run: $HOME/.local/bin/poetry run pytest
